openstack-k8s-operators/edpm-image-builder

images/edpm-hardened-uefi-centos-9-stream.yaml

This pulls in DIB_MODPROBE_BLACKLIST, DIB_BOOTLOADER_DEFAULT_CMDLINE from tripleo-common image definition. "console=" kernel arguments are left off because diskimage-builder bootloader element manages these.

Set default kernel args, modprobe blacklist

---

images/edpm-hardened-uefi-centos-9-stream.yaml

See the chain of tripleo-common changes[1] for the rationale of each removal.
[1] https://review.opendev.org/c/openstack/tripleo-common/+/881388

Remove all kernel arguments

---

README.rst
images/ironic-python-agent-rhel-9.yaml

This yaml has been tested downstream to build IPA
images on rhel-9.

Add ironic-python-agent-rhel-9.yaml

---

setup.cfg

we want `Containerfile.image` and `copy_out.sh` in `/usr/share/edpm-image-builder/ directory`
Currently, Containerfile.image file is in
`/usr/share/edpm-image-builder/Containerfile.image` directory instead of `/usr/share/edpm-image-builder/` and same for ramdisk and copy_out.sh they are in their own directory.
~~~
$ cat /usr/share/edpm-image-builder/Containerfile.image/Containerfile.image ARG BASE_IMAGE=quay.io/centos/centos:stream9-minimal ..
~~~

Fix Containerfile and copy_out.sh location

---

dib/edpm-base/package-installs.yaml

The command allows us to capture qdisc drop counter, which is useful for debugging packet loss problems.

Add tc command

---

images/edpm-hardened-uefi-centos-9-stream.yaml
images/edpm-hardened-uefi-rhel-9.yaml

It was recently removed and this causes issues with stable interface names as not removing `net.ifnames=0` from `GRUB_CMDLINE_LINUX` results in interface names in old ethx style.

Re-Add interface-names element

---

dib/edpm-partition-uefi/block-device-default.yaml
images/edpm-hardened-uefi-centos-9-stream.yaml
images/edpm-hardened-uefi-rhel-9.yaml

Building a rhel 9.2 based image is currently failing because the root partition is full.
This change increases the size of the edpm-hardened-uefi image from 4GiB to 5GiB and gives that extra space to the root partition.
Jira: OSPCIX-41

Increase edpm image and root partition by 1GiB

---

images/edpm-hardened-uefi-centos-9-stream.yaml

The aim is to make FIPs enabled by default for EDPM nodes, adding the fips element is all that is required to do that.
Jira: OSP-25912

Make edpm-hardened-uefi FIPs enabled

---

images/edpm-hardened-uefi-centos-9-stream.yaml

It appears that the host trunk.rdoproject.org has a TLS setup which is not FIPS compliant:
raise SSLError(e, request=request)\nrequests.exceptions.SSLError: HTTPSConnectionPool(host='trunk.rdoproject.org', port=443): Max retries exceeded with url: /centos9-antelope/current-podified/delorean.repo (Caused by SSLError(SSLError(1, '[SSL] unsupported (_ssl.c:1129)
Lets revert while we investigate.
This reverts commit ba423841db9e0d63583071ddf9d8372d0353fbec.

Revert "Make edpm-hardened-uefi FIPs enabled"

---

dib/ceph/REAMDE.md
dib/ceph/element-deps
dib/ceph/package-installs.yaml

It will install ceph related packages in the edpm image. It is an optional element, not enabled by default in the edpm image.

Added ceph dib element

---

images/edpm-hardened-uefi-centos-9-stream.yaml

Revert "Revert "Make edpm-hardened-uefi FIPs enabled""
Enable FIPS again, requiring a relaxation of the policy to make
connections to trunk.rdoproject.org.
This reverts commit 8691ad87988908b008d237855ba74856c9458522.
Depends-On: https://github.com/openstack-k8s-operators/install_yamls/pull/607

Revert "Revert "Make edpm-hardened-uefi FIPs enabled""

---

images/edpm-hardened-uefi-rhel-9.yaml

FIPS is currently not enabled on the CentOS image because upstream CI cannot consistently provide enough entropy to pass FIPS requirements. However FIPS still needs to be enabled by default, so this change adds FIPS support to the RHEL EDPM image.
Similar issues may be found downstream but we need to try it to find out. The workaround may be different downstream, such as getting VM based jobs to modify the image to disable FIPS on-the-fly.
Issue: OSPRH-1196

Enable FIPS for just the RHEL image

---

README.rst
images/edpm-hardened-uefi-fips.yaml
images/edpm-hardened-uefi-rhel-9.yaml
images/ironic-python-agent-fips.yaml

This simply allows a FIPS image to be created or not, rather than images
being FIPS by default.
This also reverts the RHEL image being FIPS by default. Downstream builds currently enable FIPS differently and this likely breaks the non-FIPS image build

Add separate yaml files just to enable the fips element

---

dib/host-ca/README.rst
dib/host-ca/extra-data.d/10-host-ca
dib/host-ca/pre-install.d/00-host-ca
dib/reset-bls-entries/finalise.d/49-mkdir-run-install
dib/reset-bls-entries/finalise.d/51-rm-run-install

Older versions of grub2-mkconfig will update the kernel arguments in BLS
files, but this now only happens when the --update-bls-cmdline argument
is passed, see [1]. Rather than pass --update-bls-cmdline, this change
creates the directory /run/install which restores the old behaviour for
new installs, see [2].
Issue: OSPCIX-200
[1] https://pkgs.devel.redhat.com/cgit/rpms/grub2/tree/0327-grub-mkconfig-dont-overwrite-BLS-cmdline-if-BLSCFG.patch?h=rhel-9.3.0
[2] https://pkgs.devel.redhat.com/cgit/rpms/grub2/tree/0328-grub2-mkconfig-Pass-all-boot-params-when-used-by-ana.patch?h=rhel-9.3.0

Create /run/install to restore grub2-mkconfig behaviour

---

dib/edpm-partition-uefi/finalise.d/51-efi-grub-cfg

Currently the efi grub.cfg is identical to the /boot/grub2/grub.cfg,
which only occurs thanks to a second manual call to grub2-mkconfig. This
risks out-of-band updates resulting in a stale efi grub.cfg, which in
some cases may prevent the host from booting at all.
The RHEL efi grub.cfg is a simple redirect to the /boot partition. This
change replicates this redirect.
A corresponding change to edpm-ansible will stop overwriting efi
grub.cfg with the previous approach.
Jira: OSPRH-7209

Replace efi grub.cfg with RHEL style redirect

---

zuul.d/jobs.yaml

This pr will make sure that EDPM content provider will always run on vexxhost cloud having public ips.
The EDPM dependent job will always pull the image from public IP and avoid ImagePullErr failure.

Use vexxhost nodeset in eib-content-provider-build-images

---

images/edpm-hardened-uefi-centos-9-stream.yaml

This is required to boot in some multipath environments, and should have no effect in non-multipath environments.
Since there is always a non-empty DIB_BOOTLOADER_DEFAULT_CMDLINE now, the placeholder argument and TODO is removed.
Depends-On: https://github.com/openstack-k8s-operators/edpm-image-builder/pull/33

Set kernel argument rd.multipath=default

---

images/edpm-hardened-uefi-centos-9-stream.yaml
images/edpm-hardened-uefi-rhel-9.yaml

Any console=tty0 or console=ttyS0 arguments can cause latency
regressions in networking. Setting DIB_BOOTLOADER_USE_SERIAL_CONSOLE to
false will prevent any console arguments being added, and will also
remove any console arguments from BLS entries.
Jira: OSPRH-8037

Set DIB_BOOTLOADER_USE_SERIAL_CONSOLE to false

---

.gitignore
bootc/Containerfile.centos9
bootc/Makefile
bootc/README.rst

See the README.rst for instructions.
Jira: OSPRH-10403

Build a bootc based EDPM image

---

bootc/Containerfile.centos9

Add packages to bootc image
These packages are added to the bootc image build as they are expected
to be present by edpm-ansible:
- cronie (edpm_logrotate_crond)
- openstack-network-scripts (edpm_network_config / os-net-config)
Also replace tabs with spaces.

Add packages to bootc image

---

bootc/Makefile

The OS distro might differ on the working machine from that of the bootc
image build. $REPO_SETUP_DISTRO provides a way to set the distro using
the -d argument when running repo-setup. It defaults to centos9, since
that is the default for the image build.

Add $REPO_SETUP_DISTRO

---

bootc/Containerfile.centos9

The edpm_reboot role uses needs-restarting from yum-utils, so it needs
to be installed in the bootc image.

Add yum-utils to bootc image

---

bootc/Containerfile.centos9

We may want these installed in a different specific libvirt/compute
image, but for now they are added to the base bootc image build since
libvirt is a default service.

Add libvirt packages to bootc image build

---

.github/workflows/edpm-bootc.yaml

Should be ${{ env.latesttag }} to use vars from the environment.

Correct latesttag usage

---

.github/workflows/edpm-bootc.yaml

They don't need to apply to the check-secrets job and cause it to fail.

Move workflow defaults to be under the build and push job

---

bootc/Containerfile.centos9

Mask the systemd timer that continually checks for an update container
image and will apply if one is found as it causes a reboot.

Disable bootc automatic update check and reboot

---

bootc/Containerfile.centos9

This change removes the libguestfs package from the bootc container. This is inline with efforts from the Compute team to remove this package from our dataplane nodes:
https://github.com/openstack-k8s-operators/tcib/pull/142/files#diff-20fdbc4b7badc4cdcab1a535614f5d3c52acabf84aba7661ac2e5ead8acc276eR8

Remove libguestfs in line with nova changes

---

.github/workflows/edpm-bootc.yaml
bootc/Makefile

Add workflow steps to build and push bootc qcow2 container image
Also refactors some of the targets in the bootc/Makefile so that it is
more re-usable from the github workflow.

Add workflow steps to build and push bootc qcow2 container image

---

.github/workflows/edpm-bootc.yaml

All other projects have a current-podified tag,
this change ensures our latest image also shares this tag.

Also use current-podified tag for latest image

---

bootc/.gitignore
bootc/Containerfile
bootc/Makefile
bootc/README.rst
bootc/empty.sh
bootc/install-repo-setup.sh
bootc/rhsm.sh
bootc/run-repo-setup.sh

This shares a single Containerfile for building an upstream image, and a rhel-9.4 based image using internal repositories.
This allows testing with RHEL based images, and is the first step for end users building their own images with subscription-manager.
/etc/yum.repos.d is now bind-mounted in instead of copying.
It is also possible to build rhel-9.4 based images using subscription-manager to set up the repos.
Documentation to do this is included in the README.rst but the intention
is to write some external documention which will allow end-users to
build this image without a checkout of edpm-image-builder or this
Makefile.
Images with all 3 variants have been published to test with:
quay.io/steveb/edpm-bootc:centos9
quay.io/steveb/edpm-bootc:centos9-qcow2 …

Bootc: add RHEL support with internal repos and RHSM

---

dib/edpm-base/package-installs.yaml

One "fun" issue which can happen with dib images is a vendor may have built a stock ramdisk from a build farm where the ramdisk had the artifacts to handle multipath usage, but not had the artifacts *inside* of the actual image.
Where things go sideways is when you regenerate the ramdisk with dracut and the newly build ramdisk lacks ramdisk support. This is because the ramdisk building utility uses state and artifacts from the host to incorporate into the artifact. When this occurs, even if you ask for multipath, dracut will not fail if the required additional artifacts are not found.
So the key is to have device-mapper-multipath present, which triggers the related dependency installations which enables rebuilt ramdisks to have the required artifacts for booting from multipath devices to …

Ensure device-mapper-multipath is present

---

bootc/Containerfile

Needed by edpm_growvols role
Jira: [OSPRH-11517](https://issues.redhat.com//browse/OSPRH-11517)
Signed-off-by: James Slagle <james.slagle@gmail.com>

Add growvols package to bootc image

---

bootc/Containerfile

Adds all possible package installs to the bootc image.
- **Refactor bootc/Containerfile for edpm_bootstrap**
- **Refactor bootc/Containerfile for edpm_kernel**
- **Refactor bootc/Containerfile for edpm_logrotate_crond**
- **Refactor bootc/Containerfile for edpm_network_config**
- **Refactor bootc/Containerfile for edpm_ovs**
- **Refactor bootc/Containerfile for edpm_podman**
- **Refactor bootc/Containerfile for edpm_reboot**
- **Refactor bootc/Containerfile for edpm_sshd**
- **Refactor bootc/Containerfile for edpm_tuned**
- **Refactor bootc/Containerfile for edpm_growvols**
- **Refactor bootc/Containerfile for dib/ceph**
- **Refactor bootc/Containerfile for install_os**
- **Refactor bootc/Containerfile for dib/edpm-base**
- **Refactor bootc/Containerfile for dib/ironic-agent-multipath**
- …

Refactor bootc/Containerfile for packages

---

bootc/Containerfile

This package was added to edpm_bootstrap in
https://github.com/openstack-k8s-operators/edpm-ansible/pull/980

Add sos package to bootc image build

---

.github/workflows/edpm-bootc.yaml

These volume mounts are needed when building the bootc image.

Pass volume args to buildah action

---

dib/cloud-init-network-renderer/README.md
dib/cloud-init-network-renderer/install.d/81-network-renderer
images/edpm-hardened-uefi-centos-9-stream.yaml
images/edpm-hardened-uefi-rhel-9.yaml

Give priority to network-manager as we now enable NetworkManager to update resolv.conf. Otherwise NetworkManager wipes out the dns server from resolv.conf.
jira:  https://issues.redhat.com/browse/OSPRH-19018

Add dib element to change cloud-init network renderer order
